spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.23.199:3308/spring_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: fline
    password: flineCloud@2019root
mybatis:
  config-location: classpath:mybatis-config.xml

server:
  port: 9090
